### PR TITLE
Do not bundle dependencies in cjs/esm builds

### PR DESCRIPTION
**Pull request by Andarist**
**cjs build - minified & gzipped**

**pre** - 5316 bytes
**post** - 2069 bytes

size reduction - 61% 💰

### CODE REVIEW

**Comment by banderson** [comment]
🙏

**Comment by Andarist** [comment]
@mjackson friendly 🏓

**Comment by mjackson** [comment]
Thanks, @Andarist. This means that people need to already have `React` and `ReactDOM` on the page, right?

**Comment by Andarist** [comment]
This PR introduces `external` management with `process.env.EXTERNALS`, the env var is only used for both prod & dev UMD builds with `"peers"`  value and **yes** that means users have to have `React` on the page (`react-broadcast` does not depend anyhow on `ReactDOM`), **but** that is not different from the situation before this PR. [It was already kept as external](https://github.com/ReactTraining/react-broadcast/pull/53/files#diff-d029f7a6985845ad66ad1cc90b667c17L48), just the value was statically passed into the config. Also this is the way to go, we do not want each library depending on React having to have its own copy.

The most important part of this is that without using explicit `process.env.EXTERNALS` the `external` array defaults to `deps.concat(peers)` which kicks in for both CJS & ESM bundles. Those are primarily used by bundlers / node and we shouldn't bundle deps into those bundles because then bundlers cannot dedupe this code, each such bundle keeps its own copy of those deps which increases the final bundle size.

**Comment by mjackson** [comment]
Ah, I think I see now. So when we are building the UMD bundle we say that only peers are external, but when we are building CJS or ESM we say that both peers + other deps are external, so the bundlers don't include stuff twice. I think that makes sense.

Thanks for taking such care here, @Andarist. The solution you came up with is actually quite nice. I'll get this merged and cut a new release.

**Comment by mjackson** [comment]
Published in 0.7.1

Thanks again!

**Pull request merged**
